version: '3'
services:
  broker:
    image: rabbitmq
    ports:
      - "15673:15672"  
    
  worker:
    build: 
      context: .
      dockerfile: celery.Dockerfile
    volumes:
      - ./worker_logs/:/app/logs/:rw
  
    depends_on:
      - broker
      
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./logfiles:/app/logs/:rw
    depends_on:
      - broker
      - worker
      - mongo
  mongo:
    image: mongo  
    ports: 
      - "27016:27017"
     
